name: "Test action-repository-activity"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  schedule:
    # Run the CI automatically every hour to look for flakyness.
    - cron:  '0 * * * *'

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: .github/workflows/build-and-test.sh
    - uses: ./ # Uses an action in the root directory
      id: repo_activity
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      if: always()  # required to log build failures

    # Log repository activity
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: open_issues_count
        metric-value: ${{ steps.repo_activity.outputs.open_issues_count }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: allow_merge_commit
        metric-value: ${{ steps.repo_activity.outputs.allow_merge_commit }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: allow_rebase_merge
        metric-value: ${{ steps.repo_activity.outputs.allow_rebase_merge }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: allow_squash_merge
        metric-value: ${{ steps.repo_activity.outputs.allow_squash_merge }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: archived
        metric-value: ${{ steps.repo_activity.outputs.archived }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: disabled
        metric-value: ${{ steps.repo_activity.outputs.disabled }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: forks_count
        metric-value: ${{ steps.repo_activity.outputs.forks_count }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: has_downloads
        metric-value: ${{ steps.repo_activity.outputs.has_downloads }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: has_issues
        metric-value: ${{ steps.repo_activity.outputs.has_issues }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: has_pages
        metric-value: ${{ steps.repo_activity.outputs.has_pages }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: has_projects
        metric-value: ${{ steps.repo_activity.outputs.has_projects }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: has_wiki
        metric-value: ${{ steps.repo_activity.outputs.has_wiki }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: network_count
        metric-value: ${{ steps.repo_activity.outputs.network_count }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: open_issues_count
        metric-value: ${{ steps.repo_activity.outputs.open_issues_count }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: stargazers_count
        metric-value: ${{ steps.repo_activity.outputs.stargazers_count }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: subscribers_count
        metric-value: ${{ steps.repo_activity.outputs.subscribers_count }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-name: watchers_count
        metric-value: ${{ steps.repo_activity.outputs.watchers_count }}

    # Log build success / failures
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      if: always()
